FROM --platform=linux/amd64 rust:slim as cargo-build

WORKDIR /usr/src/app

RUN apt-get update
RUN apt-get install build-essential libssl-dev openssl cmake -y

COPY . .

# RUN cargo check
RUN cargo build --release