FROM --platform=linux/amd64 messense/rust-musl-cross:x86_64-musl as cargo-build

WORKDIR /usr/src/app

COPY . .

RUN cargo build --release

FROM alpine:latest

RUN apk update \
    && apk add --no-cache ca-certificates tzdata \
    && rm -rf /var/cache/apk/*

RUN update-ca-certificates

WORKDIR /src/app

COPY .env .

COPY --from=cargo-build /usr/src/app/target/x86_64-unknown-linux-musl/release/barIO .

ENV RUST_LOG=info

# Run the application
CMD ["./barIO"]